# Generated by Django 5.2.17 on 2026-09-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formification", "0004_submission_promo_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="privacy_policy",
        ),
        migrations.AlterField(
            model_name="field",
            name="display_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="form",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PrivacyPolicy",
        ),
    ]
