name: Pull Request Checks

on: pull_request

jobs:

  run-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Check for Modified Python Files
        run: echo "gemg_py_diff=$(git diff --name-only --diff-filter=ACMRTUXB origin/$GITHUB_BASE_REF | grep  -E "(.py$)" | tr "\n" " ")" >> $GITHUB_ENV

      - name: Setup Python Linter
        if: ${{ env.gemg_py_diff != '' }}
        run: |
          python3 -m pip install -r requirements.txt

      - name: Run Black - Confirm files have been formatted using Black
        if: ${{ env.gemg_py_diff != '' }}
        run: python3 -m black ${{env.gemg_py_diff}} --check

      - name: Run Python Linter
        if: ${{ env.gemg_py_diff != '' }}
        run: python3 -m flake8 ${{env.gemg_py_diff}} --ignore=E501,F405,W503

