name: Pull Request Checks

on: pull_request

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: 'Install uv'
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: 'Install Dependencies'
        run: uv sync

      - name: 'Run Python Unit Tests'
        run: uv run python manage.py test

  run-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: uv sync

      - name: Check for Modified Python Files
        run: echo "py_diff=$(git diff --name-only --diff-filter=ACMRTUXB origin/$GITHUB_BASE_REF | grep  -E "(.py$)" | tr "\n" " ")" >> $GITHUB_ENV

      - name: Run Black - Confirm files have been formatted using Black
        if: ${{ env.py_diff != '' }}
        run: uv run black ${{env.py_diff}} --check

      - name: Run Python Linter
        if: ${{ env.py_diff != '' }}
        run: uv run flake8 ${{env.py_diff}} --ignore=E501,F405,W503